{
 "title": "BBData dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instances",
    "query": "label_values(jvm_classes_loaded_classes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Input endpoints: latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_sum{instance=~\"$instance\", uri=~\"(/objects/values)|(/input/.*)\", status=\"200\"}[1m]) / rate(http_server_requests_seconds_count{instance=~\"$instance\", uri=~\"(/objects/values)|(/input/.*)\", status=\"200\"}[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_input_rejected_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Failed logins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_login_failed_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Failed auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_auth_failed_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=~\"$instance\", status!=\"200\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "options": {
    "content": "- *rejected measures*: wrong body received in input endpoint,\n- *failed login*: wrong username/password at /login\n- *failed auth*: wrong bbuser/bbtoken \n   (using a read-only apikey on a write endpoint is not counted)"
   }
  },
  { "title": "HTTP requests (200 OK)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Throughput (requests per seconds)",
   "type": "graph",
   "description": "Throughput (requests per second): rate(timer_count[10s]) averaged over instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\".*((actuator)|(docs)).*\", status=\"200\", instance=~\"$instance\"}[1m])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "graph",
   "description": "Average latency: rate(timer_sum[10s])/rate(timer_count[10s]) averaged over instances",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(http_server_requests_seconds_sum{uri!~\".*((actuator)|(docs)).*\", instance=~\"$instance\", status=\"200\"}[1m]) / irate(http_server_requests_seconds_count{uri!~\".*((actuator)|(docs)).*\", instance=~\"$instance\", status=\"200\"}[1m])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Rejected measures",
   "type": "graph",
   "description": "Total number of measures rejected by the input API, summed across all instances",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "req." }
   ],
   "targets": [
    {
     "expr": "sum(increase(ch_derlin_input_rejected_count[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Non 200 status codes",
   "type": "graph",
   "description": "Number of requests with non 200 status codes",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "req." }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*((actuator)|(docs)).*\", status!=\"200\"}[1m])) by (method,uri,exception)",
     "legendFormat": "{{status}} {{method}} {{uri}}: {{exception}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=~\"$instance\", status!=\"200\"}) by (status, exception)",
     "legendFormat": "{{status}} {{exception}}"
    }
   ]
  },
  {
   "title": "Custom Metrics: details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "login failed",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ch_derlin_login_failed_count{instance=~\"$instance\"}) by (username)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "auth failed",
     "type": "bargauge",
     "description": "user_id that failed authentication (wrong bbuser/bbtoken)",
     "gridPos": { "h": 4, "w": 8, "x": 7, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ch_derlin_auth_failed_count{instance=~\"$instance\"}) by (user_id)",
       "legendFormat": "bbuser: {{user_id}}"
      }
     ]
    },
    {
     "title": "rejected",
     "type": "bargauge",
     "description": "user_id that failed authentication (wrong bbuser/bbtoken)",
     "gridPos": { "h": 4, "w": 8, "x": 15, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ch_derlin_input_rejected_count{instance=~\"$instance\"}) by (object_id)",
       "legendFormat": "object_id: {{object_id}}"
      }
     ]
    }
   ]
  }
 ]
}