version: "3.1"
services:

  grafana:
    image: grafana/grafana
    container_name: bbgrafana
    # user: '1000'
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: bbprometheus
    # user: '1000'
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus